// Storage static-file route (P3.T1).
//
// Mounted at `/storage`, this route serves the contents of the
// LocalStorageProvider root over HTTP — purpose-built for the Gallery
// (P2.T7) and the image detail page (P3.T6) to render thumbnails,
// previews and originals via `<img src="/storage/...">`. Without this
// route, files generated by P2.T4 / future P3.T4 sit on disk but are
// not reachable from the browser (P2 risk R-34).
//
// Scope (per docs/tasks.md P3.T1):
//   * Read-only GET (HEAD auto-aliased by Express).
//   * Defense-in-depth path validation; only paths under `trips/` may
//     be served.
//   * Content-Type from the file extension; safe default.
//   * Conservative `Cache-Control` + `X-Content-Type-Options: nosniff`.
//   * Streams the file; never buffers the whole body.
//
// Explicitly NOT in scope (deferred to later tasks):
//   * Auth / signed URLs / IP gating (design.md §12.1 "本机访问" assumption).
//   * HTTP Range requests for video seek (P9 / video work).
//   * ETag / Last-Modified / 304 negotiation.
//   * Multipart / chunked / S3 abstraction.

import { Router, type Request, type Response } from "express";

import { asyncHandler } from "../middleware/asyncHandler.js";
import { invalidKey, isStorageError, pathTraversal } from "../storage/errors.js";
import type { LocalStorageProvider } from "../storage/index.js";

export interface StorageRouterDeps {
  readonly storage: LocalStorageProvider;
}

/**
 * Allowed top-level prefixes a logical path may begin with. Today
 * only `trips/...` is laid out under the storage root (design.md
 * §5.2 — `storage/trips/{tripId}/{originals|derived|outputs}/...`).
 * Add more entries here if a new top-level directory is introduced.
 */
const ALLOWED_PREFIXES: readonly string[] = ["trips/"];

/**
 * Content-Type lookup for the file extensions we actually produce or
 * accept (requirements §7.2 supported formats + P3 derived `.webp`).
 * Unknown extensions fall back to `application/octet-stream` so the
 * browser does not try to render an arbitrary file as text/html.
 */
const CONTENT_TYPE_BY_EXT: ReadonlyMap<string, string> = new Map([
  // images
  ["jpg", "image/jpeg"],
  ["jpeg", "image/jpeg"],
  ["png", "image/png"],
  ["webp", "image/webp"],
  ["heic", "image/heic"],
  ["gif", "image/gif"],
  // videos
  ["mp4", "video/mp4"],
  ["mov", "video/quicktime"],
  ["m4v", "video/x-m4v"],
  ["avi", "video/x-msvideo"],
  ["mkv", "video/x-matroska"],
]);

const DEFAULT_CONTENT_TYPE = "application/octet-stream";

/**
 * Conservative cache window. Files under `trips/` are effectively
 * immutable post-write (originals never overwritten per CLAUDE.md
 * §2.1; derived files default `overwrite=false` per P0.T7). One hour
 * is a low-risk default — long enough to amortise the Gallery first
 * paint, short enough that any future invalidation strategy can take
 * over without long-lived stale entries.
 */
const CACHE_CONTROL = "private, max-age=3600";

export function makeStorageRouter(deps: StorageRouterDeps): Router {
  const router = Router();

  // GET /storage/<logical-path>
  //
  // Express's `/*` wildcard captures everything after the mount prefix
  // and exposes it as `req.params[0]` (without the leading slash). We
  // route a single handler for all paths so validation logic lives in
  // one place.
  router.get(
    "/*",
    asyncHandler(async (req, res) => {
      const raw = readWildcard(req);
      const logicalPath = validateLogicalPath(raw);

      // `storage.read()` runs the full 3-layer pathUtils check
      // (per-segment regex, POSIX normalisation, post-resolve
      // `path.relative` confirmation) and then opens a read stream.
      // Missing files surface as STORAGE_NOT_FOUND (404) via the
      // global error middleware. Our pre-validation above means we
      // never reach here with `..` / null bytes.
      const stream = await deps.storage.read(logicalPath);

      res.setHeader("Content-Type", contentTypeFor(logicalPath));
      res.setHeader("Cache-Control", CACHE_CONTROL);
      // Tells browsers not to guess a different type from sniffing
      // the bytes (e.g. promote `.bin` to `text/html`). Standard
      // hardening, cheap to apply.
      res.setHeader("X-Content-Type-Options", "nosniff");

      attachStreamErrorGuards(stream, res);
      stream.pipe(res);
    }),
  );

  return router;
}

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

function readWildcard(req: Request): string {
  // Express types the wildcard match loosely; coalesce to "" so the
  // empty / undefined case takes the same rejection path as a missing
  // path segment rather than crashing.
  const params = req.params as Record<string | number, string | undefined>;
  return params[0] ?? "";
}

/**
 * Reject any path that:
 *   - is empty
 *   - contains null bytes or backslashes (Windows / injection)
 *   - has `.` / `..` / empty segments (prefix-bypass / traversal)
 *   - does not start with a whitelisted top-level prefix
 *
 * We deliberately do NOT normalise `..` away (unlike Node's
 * `path.normalize`) because a request that contains `..` is by
 * definition adversarial in this context: the frontend constructs
 * URLs from `originalPath` / `thumbnailPath` values that the backend
 * itself wrote, and those never contain `..`.
 */
function validateLogicalPath(raw: string): string {
  if (raw.length === 0) {
    throw invalidKey("logicalPath is empty");
  }
  if (raw.includes("\0")) {
    throw invalidKey("logicalPath contains null byte");
  }
  if (raw.includes("\\")) {
    throw invalidKey("logicalPath must use forward slashes only");
  }
  for (const seg of raw.split("/")) {
    if (seg === "." || seg === "..") {
      throw pathTraversal(`logicalPath contains forbidden segment "${seg}": ${raw}`);
    }
    if (seg.length === 0) {
      throw invalidKey(`logicalPath contains an empty segment: ${raw}`);
    }
  }
  if (!ALLOWED_PREFIXES.some((p) => raw.startsWith(p))) {
    throw invalidKey(
      `logicalPath must start with one of: ${ALLOWED_PREFIXES.map((p) => `"${p}"`).join(", ")}`,
    );
  }
  return raw;
}

function contentTypeFor(logicalPath: string): string {
  const dotIdx = logicalPath.lastIndexOf(".");
  if (dotIdx < 0 || dotIdx === logicalPath.length - 1) {
    return DEFAULT_CONTENT_TYPE;
  }
  const ext = logicalPath.slice(dotIdx + 1).toLowerCase();
  return CONTENT_TYPE_BY_EXT.get(ext) ?? DEFAULT_CONTENT_TYPE;
}

/**
 * Late-stage stream failure: the file existed when `storage.read()`
 * resolved, but a disk-level IO error happens mid-pipe. We can't
 * switch the HTTP response to a JSON envelope once any bytes (or
 * headers) have been sent, so we either render a 500 JSON if nothing
 * was flushed yet, or destroy the connection so the client sees a
 * truncated read instead of a silently-successful partial body.
 */
function attachStreamErrorGuards(stream: NodeJS.ReadableStream, res: Response): void {
  stream.on("error", (err) => {
    if (res.headersSent) {
      res.destroy(err instanceof Error ? err : new Error(String(err)));
      return;
    }
    if (isStorageError(err)) {
      res.status(err.statusCode).json({
        error: { code: err.code, message: err.message },
      });
      return;
    }
    res.status(500).json({
      error: { code: "STORAGE_IO_ERROR", message: "stream read failed" },
    });
  });
}
